language: python
sudo: required
python:
  - "2.7"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -e .
script:
  - pytest --pep8 sda --cov sda/ --cov-report term-missing test/
after_success:
  - coveralls